### ISSUE TITLE
Default Home app is missing

### ISSUE THREAD

**Issue by classifaddict** [texperience/wagtail-openshift-quickstart#1]
It would be good for newcomers starting with Wagtail tutorial to have the default Home app created by "wagtail start wagtail_openshift_quickstart".

**Comment by timorieber** [comment]
Thanks for your suggestion!

The {{wagtail start}} command creates a whole new project with some demo applications. However, this quickstart aims to be as minimal as possible to allow all further use cases and makes no assumptions what the developer is going to achieve in the next steps.

You may create the wagtail project template somewhere on your local machine and copy the home app into this repository.

**Comment by classifaddict** [comment]
Thanks for your answer,

I got your point.

Stripping down Wagtail reveals his magic parts, it is very confusing for a
newcomer starting with Wagtail tutorial.
But I guess that the ones evaluating Wagtail and Openshift at the same time
starting with your excellent template will be very rare.

This is promising so far and will be almost perfect if I can plug Django-
allauth and Django-storage.

Thanks,
Olivier.

2016-06-21 7:14 GMT+02:00 Timo Rieber <notifications@github.com>:
